name: Deploy to Amplify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-west-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Amplify CLI
        run: npm install -g @aws-amplify/cli

      - name: Check if Amplify is Initialized
        run: amplify status || amplify init --yes \
          --amplify "{\"envName\":\"dev\"}" \
          --frontend "{\"framework\":\"javascript\",\"config\":{\"SourceDir\":\"src\",\"DistributionDir\":\"build\",\"BuildCommand\":\"npm run build\",\"StartCommand\":\"npm start\"}}" \
          --providers "{\"awscloudformation\":{\"configLevel\":\"project\",\"useProfile\":false,\"accessKeyId\":\"${{ secrets.AWS_ACCESS_KEY_ID }}\",\"secretAccessKey\":\"${{ secrets.AWS_SECRET_ACCESS_KEY }}\",\"region\":\"${{ env.AWS_REGION }}\"}}"

      - name: Deploy to Amplify
        run: amplify publish
